services:

  bot:
    container_name: astrobot
    restart: always
    user: "1000:1000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: local-astrobot
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"  # expose health check port
    volumes:
      - type: bind
        source: ./index.js
        target: /app/index.js
      - ./src:/app/src